// <auto-generated />
namespace PTPMQL07.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Alter_Column_NgayDi_NgayDen : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Alter_Column_NgayDi_NgayDen));
        
        string IMigrationMetadata.Id
        {
            get { return "202105121732329_Alter_Column_NgayDi_NgayDen"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
